#env_params:
task_name: 'ReorientUp'
task_description:
  'screw bottle cap for opening or closing'

dexrep:
  sample_method: 'average'
  sample_num_points: 2048
  batch_norm_pnfeat: False

env:
  numEnvs: 80
  envSpacing: 0.75
  episodeLength: 600
  random_prior: True
  repose_z: True
  enableDebugVis: True
  aggregateMode: 1

  asset:

    assetRoot: "./asset"
    assetFileNameRobot: "shadow_hand/mjcf/open_ai_assets/hand/shadow_hand_sensor.xml"
    assetFileNameObj: "/reorient_up/"

  env_dict:
    - ycb_003_cracker_box
    - ycb_005_tomato_soup_can
#      - ddg-ycb_012_strawberry
#      - ddg-ycb_013_apple
#      - ddg-ycb_014_lemon
#      - ddg-ycb_015_peach
#      - ddg-ycb_017_orange
#      - ddg-ycb_019_pitcher_base
#      - ddg-ycb_021_bleach_cleanser
#      - ddg-ycb_036_wood_block
#      - ddg-ycb_038_padlock
#      - ddg-ycb_040_large_marker
#      - ddg-ycb_054_softball
#      - ddg-ycb_055_baseball
#      - ddg-ycb_056_tennis_ball
#      - ddg-ycb_057_racquetball
#      - ddg-ycb_058_golf_ball
#      - ddg-ycb_065-a_cups
#      - ddg-ycb_065-b_cups
#      - ddg-ycb_065-c_cups
#      - ddg-ycb_065-e_cups
#      - ddg-ycb_065-f_cups
#      - ddg-ycb_070-a_colored_wood_blocks
#      - ddg-ycb_070-b_colored_wood_blocks
#      - ddg-ycb_072-a_toy_airplane
#      - ddg-ycb_072-b_toy_airplane
#      - ddg-ycb_077_rubiks_cube
  # env param
  obs_type:
    "DexRep"
  obs_dim:
    prop: 211 # 211 #propriception
    dexrep_sensor: 1080
    dexrep_pnl: 1280

  action_dim: 20

  img_w: 224
  img_h: 224

  vision:
    camera:
      # relative to table center
      eye: [
        [ -0.05, 0.01, 0.24 ],
      ]
      lookat: [
        [ 0.0, -0.36, 0.0 ], # camera cannot look at accurate -z
      ]

  random_load:
    sequential: True
    num_obj_per_env: 1  # maximum a * b * 4 + 1 # 257
    obj_width: 0.1
    a: 2 #4
    b: 2

  clip_observations: 5.0
  clip_actions: 1.0


  stiffnessScale: 1.0
  forceLimitScale: 1.0
  useRelativeControl: False
  dofSpeedScale: 20.0
  actionsMovingAverage: 1.0
  controlFrequencyInv: 1 # 60 Hz

  startPositionNoise: 0.01
  startRotationNoise: 0.0

  resetPositionNoise: 0.01
  resetRotationNoise: 0.0
  resetDofPosRandomInterval: 0.2
  resetDofVelRandomInterval: 0.0

  # Random forces applied to the object
  forceScale: 0.0
  forceProbRange: [0.001, 0.1]
  forceDecay: 0.99
  forceDecayInterval: 0.08

  distRewardScale: -10
  transition_scale: 0.05
  orientation_scale: 0.5
  rotRewardScale: 1.0
  rotEps: 0.1
  actionPenaltyScale: -0.0002
  reachGoalBonus: 250
  fallDistance: 0.24
  fallPenalty: 0.0

  objectType: "block" # can be block, egg or pen
  observationType: "full_state" # can be "openai", "full_no_vel", "full", "full_state"
  asymmetric_observations: False
  successTolerance: 0.1
  printNumSuccesses: False
  maxConsecutiveSuccesses: 0




task:
  randomize: False
  randomization_params:
    frequency: 600   # Define how many simulation steps between generating new randomizations
    observations:
      range: [ 0, .002 ] # range for the white noise
      range_correlated: [ 0, .001 ] # range for correlated noise, refreshed with freq `frequency`
      operation: "additive"
      distribution: "gaussian"
      schedule: "linear"   # "constant" is to turn on noise after `schedule_steps` num steps
      schedule_steps: 40000
    actions:
      range: [ 0., .05 ]
      range_correlated: [ 0, .015 ] # range for correlated noise, refreshed with freq `frequency`
      operation: "additive"
      distribution: "gaussian"
      schedule: "linear"  # "linear" will linearly interpolate between no rand and max rand
      schedule_steps: 40000
    sim_params:
      gravity:
        range: [ 0, 0.4 ]
        operation: "additive"
        distribution: "gaussian"
        schedule: "linear"  # "linear" will linearly interpolate between no rand and max rand
        schedule_steps: 40000
    actor_params:
      hand:
        color: True
        tendon_properties:
          damping:
            range: [ 0.3, 3.0 ]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
          stiffness:
            range: [ 0.75, 1.5 ]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
        dof_properties:
          damping:
            range: [ 0.3, 3.0 ]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
          stiffness:
            range: [ 0.75, 1.5 ]
            operation: "scaling"
            distribution: "loguniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
          lower:
            range: [ 0, 0.01 ]
            operation: "additive"
            distribution: "gaussian"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
          upper:
            range: [ 0, 0.01 ]
            operation: "additive"
            distribution: "gaussian"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
        rigid_body_properties:
          mass:
            range: [ 0.5, 1.5 ]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
        rigid_shape_properties:
          friction:
            num_buckets: 250
            range: [ 0.7, 1.3 ]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
      object:
        scale:
          range: [ 0.95, 1.05 ]
          operation: "scaling"
          distribution: "uniform"
          schedule: "linear"  # "linear" will scale the current random sample by ``min(current num steps, schedule_steps) / schedule_steps`
          schedule_steps: 30000
        rigid_body_properties:
          mass:
            range: [ 0.5, 1.5 ]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"  # "linear" will scale the current random sample by ``min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000
        rigid_shape_properties:
          friction:
            num_buckets: 250
            range: [ 0.7, 1.3 ]
            operation: "scaling"
            distribution: "uniform"
            schedule: "linear"  # "linear" will scale the current random sample by `min(current num steps, schedule_steps) / schedule_steps`
            schedule_steps: 30000


sim:
  dt: 0.01667 # 1/60
  substeps: 2
  physx:
    num_threads: 4
    solver_type: 1
    num_position_iterations: 8
    num_velocity_iterations: 0
    contact_offset: 0.002
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
    always_use_articulations: False

video_path : 'runs/videos'

